# Generated by Django 5.0.8 on 2024-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        help_text="someone@kartek.com", max_length=254, unique=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField(null=True)),
                ("position", models.CharField(max_length=50)),
                ("contract_type", models.CharField(max_length=50)),
                ("hire_date", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("department", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=100)),
                ("birthdate", models.DateField()),
                ("photo", models.ImageField(upload_to="employee_photos/")),
                ("password", models.CharField(max_length=120)),
            ],
        ),
    ]
