# Generated by Django 5.0.8 on 2024-08-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr_app", "0002_employee_absence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="absence",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
