# Generated by Django 5.1 on 2024-08-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_alter_employee_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('requirements', models.CharField(max_length=10000)),
                ('active_until', models.DateField()),
                ('department_type', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('status', models.CharField(default='Sourced', max_length=100)),
                ('CV', models.FileField(upload_to='cvs/')),
                ('phone', models.CharField(max_length=100)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='hr_app.recruitment')),
            ],
        ),
    ]
