# Generated by Django 5.1 on 2024-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_recruitment_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='department_type',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='requirements',
            field=models.TextField(),
        ),
    ]
