# Generated by Django 5.1 on 2024-08-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_rename_department_type_recruitment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
    ]
