# Generated by Django 5.1 on 2024-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_alter_candidate_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('sourced', 'Sourced'), ('in_progress', 'In Progress'), ('interview', 'Interview'), ('hired', 'Hired'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], default='sourced', max_length=100),
        ),
    ]
