# Generated by Django 5.1 on 2024-08-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_alter_candidate_options_candidate_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='order',
        ),
    ]
