# Generated by Django 5.1 on 2024-08-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0008_alter_candidate_options_remove_candidate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Sourced', 'Sourced'), ('In Progress', 'In Progress'), ('Interview', 'Interview'), ('Hired', 'Hired'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected')], default='Sourced', max_length=100),
        ),
    ]
