# Generated by Django 5.1 on 2024-08-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0011_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('', ''), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=100),
        ),
    ]
