# Generated by Django 5.1 on 2024-08-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0013_events'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='tblevents',
        ),
    ]
