# Generated by Django 5.1 on 2024-09-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0017_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
    ]
